### ISSUE TITLE
Configuration on NaiveSafariView

### ISSUE THREAD

**Issue by yixe** [stleamist/BetterSafariView#2]
It seems there is no way to configure NaiveSafariView at the moment.
For example to add `entersReaderIfAvailable: true` to a sheet that has NaiveSafariView as its content.

**Comment by stleamist** [comment]
For the moment, you need to implement something like `NaiveSafariView` to use on SwiftUI native view modifiers. It's because the current version of `SafariView` is actually not a `View` but just a simple struct used for internal `SafariViewHosting`.

Its `View` conformance had been implemented during the preparation process of v2.0.0 update, but was removed just before the release(c8a0d7e) due to some concerns about project complexity.

For the use cases you mentioned, I’ll release a new update soon that adds `View` conformance to the `SafariView`.

Thank you for pointing out this case. 😃

**Comment by stleamist** [comment]
Starting from [v2.2.0](https://github.com/stleamist/BetterSafariView/releases/tag/v2.2.0), you can now pass the `SafariView` as a `View` to the `.sheet()` and `.fullScreenCover()` modifiers.

Thank you for your contribution. 🤗
