### ISSUE TITLE
Errors when adding swift package via xcode

### ISSUE THREAD

**Issue by Andrewpk** [stleamist/BetterSafariView#3]
When adding the package as a dependency from xcode's add swift package dependency, I keep getting errors of this sort like it's not actually linking against the package properly:
`Cannot convert value of type 'Example_App_Name.SafariView' to closure result type 'BetterSafariView.SafariView'`

I've done the old derived data dance and still no luck, yet the demo project works fine.

Update:
I had been developing an app with xcode 12 beta, switched to xcode 11 & iOS 13 so I could get a testflight build uploaded, and that's when I started seeing breakage.
I just opened the demo app in xcode 11 and changed the deployment target to ios 13 and I see that there are quite a few errors, so now it makes a lot more sense.

I originally thought it was maybe a problem with the way I included the dep, or the `SafariView.Configuration` convenience init, but it looks like there are other issues.

**Comment by stleamist** [comment]
Hi @Andrewpk,

It seems like you have defined another `SafariView` symbol in your project namespace. That error means you may have passed your own `SafariView` type to the `.safariView()` modifier, instead of BetterSafariView's.

To resolve this naming conflict, you could try one of the following:
1. Rename your own `SafariView` definition, or remove it.
2. Pass it to the `.safariView()` modifier including its module name: `BetterSafariView.SafariView`.

Also, as it says on [README](https://github.com/stleamist/BetterSafariView#demo), the demo wouldn't work on iOS 13, since it uses new features introduced in iOS 14 such as `ColorPicker`.

I would appreciate it if you keep me updated on this issue. 😃

**Comment by Andrewpk** [comment]
I forgot I had a previous extension and some other nonsense due to me working too late on this project. I apologize - wholly my mistake, works great in Xcode 11!
